- name: Configure Kubernetes
  hosts: kubernetes
  tasks:
    - name: Waiting for API server to become ready
      wait_for:
        host: "{{apiserver_ip}}"
        port: 443
    - name: Heapster
      command: kubectl --kubeconfig kubeconfig --namespace kube-system apply -f addons/files/heapster.yaml
    - name: nginx ingress loadbalancer
      command: kubectl --kubeconfig kubeconfig --namespace kube-system apply -f addons/files/nginx-lb.yaml
    - name: kube-lego certificate manager
      command: kubectl --kubeconfig kubeconfig --namespace kube-system apply -f addons/files/kube-lego.yaml
    - name: Weave network plugin
      command: kubectl --kubeconfig kubeconfig --namespace kube-system apply -f addons/files/weave.yaml
    - name: Rendered template directory
      file: path=addons/templates/.rendered state=directory
    - name: DNS template
      template:
        src: addons/templates/dns.yaml
        dest: addons/templates/.rendered/dns.yaml
    - name: DNS
      command: kubectl --kubeconfig kubeconfig --namespace kube-system apply -f addons/templates/.rendered/dns.yaml
    - name: Dashboard template
      template:
        src: addons/templates/dashboard.yaml
        dest: addons/templates/.rendered/dashboard.yaml
    - name: Dashboard
      command: kubectl --kubeconfig kubeconfig --namespace kube-system apply -f addons/templates/.rendered/dashboard.yaml
