- name: Configure Kubernetes
  hosts: kubernetes
  tasks:
    - name: Waiting for API server to become ready
      wait_for:
        host: "{{hostvars[groups['master'][0]]['ansible_host']}}"
        port: 443
    - name: Heapster
      command: kubectl --kubeconfig kubeconfig --namespace kube-system apply -f configure_cluster/files/heapster.yaml
    - name: Kube state metrics
      command: kubectl --kubeconfig kubeconfig --namespace kube-system apply -f configure_cluster/files/kube-state-metrics.yaml
    - name: nginx ingress loadbalancer
      command: kubectl --kubeconfig kubeconfig --namespace kube-system apply -f configure_cluster/files/nginx-lb.yaml
    - name: kube-lego certificate manager
      command: kubectl --kubeconfig kubeconfig --namespace kube-system apply -f configure_cluster/files/kube-lego.yaml
    - name: Weave network plugin
      command: kubectl --kubeconfig kubeconfig --namespace kube-system apply -f configure_cluster/files/weave.yaml
    - name: Rendered template directory
      file: path=configure_cluster/templates/.rendered state=directory
    - name: DNS template
      template:
        src: configure_cluster/templates/dns.yaml
        dest: configure_cluster/templates/.rendered/dns.yaml
    - name: DNS
      command: kubectl --kubeconfig kubeconfig --namespace kube-system apply -f configure_cluster/templates/.rendered/dns.yaml
    - name: Dashboard template
      template:
        src: configure_cluster/templates/dashboard.yaml
        dest: configure_cluster/templates/.rendered/dashboard.yaml
    - name: Dashboard
      command: kubectl --kubeconfig kubeconfig --namespace kube-system apply -f configure_cluster/templates/.rendered/dashboard.yaml
    - name: Fetch RBAC policies from Git
      git:
        repo: ssh://git@scm.uninett.no/system/kubernetes-rbac-policies.git
        dest: configure_cluster/.kubernetes-rbac-policies
    - name: Apply RBAC policies
      command: kubectl --kubeconfig kubeconfig --namespace kube-system apply -f configure_cluster/.kubernetes-rbac-policies/pilot
