- name: Configure Kubernetes
  hosts: kubernetes
  vars:
    template_addons:
      - dns
      - dashboard
    file_addons:
      - heapster
      - kube-state-metrics
      - nginx-lb
      - kube-lego
      - weave
  tasks:
    - name: Waiting for API server to become ready
      wait_for:
        host: "{{hostvars[groups['master'][0]]['ansible_host']}}"
        port: 443
    - name: Deploy addons from file
      command: kubectl --kubeconfig kubeconfig --namespace kube-system apply -f configure_cluster/files/{{ item }}.yaml
      with_items: "{{ file_addons }}"
    - name: Rendered template directory
      file: path=configure_cluster/templates/.rendered state=directory
    - name: Render templates
      template:
        src: configure_cluster/templates/{{ item }}.yaml
        dest: configure_cluster/templates/.rendered/{{ item }}.yaml
      with_items: "{{ template_addons }}"
    - name: Deploy addons from templates
      command: kubectl --kubeconfig kubeconfig --namespace kube-system apply -f configure_cluster/templates/.rendered/{{ item }}.yaml
      with_items: "{{ template_addons }}"
    - name: Fetch RBAC policies from Git
      git:
        repo: ssh://git@scm.uninett.no/system/kubernetes-rbac-policies.git
        dest: configure_cluster/.kubernetes-rbac-policies
    - name: Apply RBAC policies
      command: kubectl --kubeconfig kubeconfig --namespace kube-system apply -f configure_cluster/.kubernetes-rbac-policies/pilot
