- name: configure master nodes
  hosts: master
  remote_user: root
  become: yes
  vars:
    apiserver_address: http://127.0.0.1:8080
  tasks:
    - name: Create kubernetes manifests folder
      file:
        path: /etc/kubernetes/manifests
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: Configure kube apiserver
      template:
        src: masters/templates/kube-apiserver.yaml
        dest: /etc/kubernetes/manifests/kube-apiserver.yaml
        owner: core
        group: core
        mode: 0644
    - name: Configure kube proxy
      template:
        src: masters/templates/kube-proxy.yaml
        dest: /etc/kubernetes/manifests/kube-proxy.yaml
        owner: core
        group: core
        mode: 0644
    - name: Configure kube controller manager
      template:
        src: masters/templates/kube-controller-manager.yaml
        dest: /etc/kubernetes/manifests/kube-controller-manager.yaml
        owner: core
        group: core
        mode: 0644
    - name: Configure kube scheduler
      template:
        src: masters/templates/kube-scheduler.yaml
        dest: /etc/kubernetes/manifests/kube-scheduler.yaml
        owner: core
        group: core
        mode: 0644
    - name: Configure kube scheduler
      template:
        src: masters/templates/apiserver-kubeconfig.yaml
        dest: /etc/kubernetes/apiserver-kubeconfig.yaml
        owner: core
        group: core
        mode: 0644
    - name: Copy kubernetes service account key
      copy:
        src: ../masters/service_account/{{inventory_hostname}}.pem
        dest: /etc/kubernetes/service-key.pem
        owner: root
        group: root
        mode: 0600
    - name: Configure kubelet
      template:
        dest: /etc/systemd/system/kubelet.service
        src: masters/templates/kubelet-apiserver.service
        owner: root
        group: root
        mode: 0644
      notify:
        - reload systemd
    - name: run docker
      service: name=docker state=started enabled=yes
    - name: run kubelet
      service: name=kubelet state=started enabled=yes
  handlers:
    - name: reload systemd
      command: systemctl daemon-reload
    - name: restart systemd-networkd
      service: name=systemd-networkd state=restarted
