- name: Set node hostname
  command: hostnamectl set-hostname {{ inventory_hostname }}
  when: ansible_fqdn != "{{ inventory_hostname }}.node.cluster.local"
  register: hostname_updated
- name: Preserve node hostname
  copy:
    content: |
      preserve_hostname: true
    dest: /etc/cloud/cloud.cfg.d/99_hostname.cfg
    owner: root
    group: root
    mode: 0644
  when: hostname_updated.changed
- name: Reload facts
  setup:
    gather_subset=network
  when: hostname_updated.changed
