- name: generate /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
- name: Install socat
  yum:
    name: socat
- name: Install python-docker-py
  yum:
    name: python-docker-py
