- name: restart systemd-networkd
  service: name=systemd-networkd state=restarted
- name: Create kubernetes ssl folder
  file:
    path: /etc/kubernetes/ssl
    state: directory
    owner: root
    group: root
    mode: 0755
- name: Copy kubernetes ca certificate
  copy:
    src: ../kubernetes/ca.pem
    dest: /etc/kubernetes/ssl/ca.pem
    owner: root
    group: root
    mode: 0644
- name: Copy kubernetes node certificate
  copy:
    src: ../kubernetes/{{inventory_hostname}}.pem
    dest: /etc/kubernetes/ssl/node.pem
    owner: root
    group: root
    mode: 0644
- name: Copy kubernetes node key
  copy:
    src: ../kubernetes/{{inventory_hostname}}-key.pem
    dest: /etc/kubernetes/ssl/node-key.pem
    owner: root
    group: root
    mode: 0600
