apiVersion: v1
kind: Config
clusters:
- name: ${cluster_name}
  cluster:
    server: ${apiserver_address}
users:
- name: kubelet
contexts:
- context:
    cluster: ${cluster_name}
    user: kubelet
  name: kubelet-context
current-context: kubelet-context
