- name: Create overrides folder for locksmithd
  file:
    path: /etc/systemd/system/locksmithd.service.d
    state: directory
    owner: root
    group: root
    mode: 0755
- name: Configure locksmithd
  template:
    dest: /etc/systemd/system/locksmithd.service.d/locksmithd.conf
    src: locksmithd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart locksmithd
