- name: Create kubernetes directory
  file:
    path: /opt/kubernetes
    state: directory
    owner: root
    group: root
    mode: 0755
- name: Download kubelet
  shell: >
    curl -sSL https://dl.k8s.io/v{{ k8s_ver }}/kubernetes-server-linux-amd64.tar.gz
    | tar --extract --gzip --to-stdout kubernetes/server/bin/kubelet >/opt/kubernetes/kubelet-{{ k8s_ver }}.new
    && chmod 0755 /opt/kubernetes/kubelet-{{ k8s_ver }}.new
    && mv /opt/kubernetes/kubelet-{{ k8s_ver }}.new /opt/kubernetes/kubelet-{{ k8s_ver }}
  args:
    creates: /opt/kubernetes/kubelet-{{ k8s_ver }}
- name: Kubelet manifest directory
  file:
    path: /etc/kubernetes/manifests
    state: directory
    owner: root
    group: root
    mode: 0755
- name: Configure kubelet
  template:
    dest: /etc/systemd/system/kubelet.service
    src: kubelet.service.j2
    owner: root
    group: root
    mode: 0644
  register: kubelet_svc
- name: Reloading systemd
  command: systemctl daemon-reload
  when: kubelet_svc.changed
- name: run kubelet
  service: name=kubelet state=started enabled=yes
