- name: reload systemd
  command: systemctl daemon-reload
- name: restart systemd-networkd
  service: name=systemd-networkd state=restarted
- name: restart kubelet
  service: name=kubelet state=restarted
