- name: Work arond docker blocking IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_file: /etc/sysctl.d/00-forwarding.conf
- name: Set up Docker YUM repository
  yum_repository:
    name: dockerrepo
    description: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    gpgcheck: yes
    gpgkey: https://yum.dockerproject.org/gpg
- name: Install Docker
  yum:
    name: "{{ docker_ver }}"
- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true
