apiVersion: v1
kind: Namespace
metadata:
  name: scratch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: scratch-internal-edit
  namespace: scratch
subjects:
  - kind: Group
    name: scm_internal
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
