apiVersion: v1
kind: Config
clusters:
- name: {{cluster_name}}
  cluster:
    server: https://127.0.0.1:8383
    certificate-authority: /etc/kubernetes/ssl/ca.pem
users:
- name: kubelet
  user:
    client-certificate: /etc/kubernetes/ssl/node.pem
    client-key: /etc/kubernetes/ssl/node-key.pem
contexts:
- context:
    cluster: {{cluster_name}}
    user: kubelet
  name: kubelet-context
current-context: kubelet-context
