- name: Generate node Kubernetes certificates
  command: ./tls/generate_cert.sh kubernetes server {{ ansible_fqdn }} apiserver.cluster.local {{ apiserver_service_ip }} {{ public_ip }}
  register: create_kubernetes_cert
  changed_when: "create_kubernetes_cert.rc != 2"
  failed_when: "create_kubernetes_cert.rc not in (0, 2)"
  delegate_to: localhost
  become: false
- name: Make Kubernetes certificate folder
  file:
    state: directory
    path: /etc/kubernetes/ssl
    owner: root
    group: root
    mode: 0755
- name: Copy Kubernetes CA certificate
  copy:
    src: tls/kubernetes/ca.pem
    dest: /etc/kubernetes/ssl/ca.pem
    owner: root
    group: root
    mode: 0644
- name: Copy Kubernetes node certificate
  copy:
    src: tls/kubernetes/{{ ansible_fqdn }}.pem
    dest: /etc/kubernetes/ssl/node.pem
    owner: root
    group: root
    mode: 0644
- name: Copy Kubernetes node private key
  copy:
    src: tls/kubernetes/{{ ansible_fqdn }}-key.pem
    dest: /etc/kubernetes/ssl/node-key.pem
    owner: root
    group: root
    mode: 0600
- name: Copy Kubernetes service key
  copy:
    src: tls/kubernetes-service-key.pem
    dest: /etc/kubernetes/service-key.pem
    owner: root
    group: root
    mode: 0600
- name: Waiting for Etcd to become ready
  wait_for:
    host: "{{ ansible_default_ipv4['address'] }}"
    port: 2379
- name: Add apiserver manifest
  template:
    src: kube-apiserver.yaml.j2
    dest: /etc/kubernetes/manifests/kube-apiserver.yaml
    owner: root
    group: root
    mode: 0644
